name: "Release"

on: 
  push:
    branches:
      - "main"
    tags:
      - "v*"
      - "rc*"

jobs:
  Release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go get
      - run: make build
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/looks-darwin-amd64
            bin/looks-darwin-arm64
            bin/looks-linux-amd64
            bin/looks-linux-arm64
            bin/looks-windows-amd64.exe
            bin/looks-windows-arm64.exe
    